### ISSUE TITLE
Plugin workflows

### ISSUE THREAD

**Issue by azaozz** [WordPress/design-experiments#4]
Think it would be helpful to try and define in more detail the "expected/desired workflow" for the two types of users:
1. People that want to test experiments.
2. People that want to add experiments.

The first case seems pretty straightforward. The plugin can have a "release" and be updated (in the WP plugins repo) every time a new experiment is added. Then people that are testing can update it from whitin WP and get the new experiment(s). There are couple of minor downsides to that:
- The plugin will need to be "released" and an updated version added to the WP plugins directory every time a new experiment is added. This is still somewhat manual process and needs a maintainer to do.
- If there are a lot of experiments, it may get a bit confusing for the testers. If that happens:
  - Would there be a way to retire experiments?
  - Should it be possible to test more than one experiment at the same time? (I'm thinking "No" and if an experiment is an extension/tweak of another experiment, it should start by forking the "parent" CSS file. This may be a bit... too much in cases where only a few minor changes are needed, but would keep things simpler for testers imho).

The second "workflow" is more complex. One thing to watch out for is that if the new, "unpublished" experiment is in the plugin's directory, and the plugin is updated from WP, it will be deleted. Similarly any changes/tweaks to existing experiments will just "disappear".

That will happen even when the plugin is forked with git or the GH app and placed in `wp-content/plugins` (of course in this case the user will be able to revert the plugin update and get their previously changed files back).

Few ways to prevent this are:
1. Do not add the plugin to the WP plugins directory. Then the users will always have to "fork" it and update it with git/the GH app. This would make the plugin a "purely" developer's tool: need for a GH account, GH app installed, some basic understanding of how versioning works, etc. Not sure how desirable that'd be. Also, perhaps that will make it less discoverable.
2. Store the new experiments outside the plugin's directory. That should be pretty easy to set up (imho) and would work well for both workflows. We can make the plugin look at a "neighbour" directory for any new CSS files/experiments (or sub-directories?) and show them in the settings. Can also have a "Start a new experiment" button that will create that dir if it doesn't exist, copy the template to it, rename it, and perhaps create a PR when the experiment is ready to be published.
3. Store the new experiments in the DB. That would bring pretty much the same benefits as storing the experiments in a separate directory, but would work a bit differently for the "Add new experiment" part, and the way experiments are "published". Thinking that if we run into problems with 2 above, can try doing this.

**Comment by karmatosed** [comment]
I really appreciate the thorough view @aaozz. I do wonder though for the sake of just getting something out, what the delicious, cupcake version of this would be. I sort of feel as is the spirit of this plugin releasing as a mvp sooner over later is great, it can and should evolve. This is after all not a product just a place to explore.

With that in mind, what is the smallest change we can make to what we have now? Can it just for now be released here and people download and that's it? I don't think we need to in this case skip ahead to future vision. I know I say this usually being of the full product planning mindset. In this instance though it's a playground to explore.

**Comment by kjellr** [comment]
Thanks, @azaozz!

1. People that want to test experiments.
2. People that want to add experiments.

This is a great framing. This repo was mostly born out of the desire to do both at once: I wanted to build and test out an idea. I had to add CSS to WP-Admin in order to do that, so I built a simple plugin to do that. And here we are. 😄 

I think in general, the target audience here is people who want to build (add) experiments: without them, this plugin doesn't really need to exist. Having this be easily testable by non-builders is totally necessary too, but in the near term, I'm happy just having them download and install a plugin to do that. If the experiment has been merged into the plugin, people who are only testing won't need GitHub logins or anything — they'll just need to download a zip file of the plugin and upload it to their site. This seems fairly reasonable to me for what this is. 

> The plugin will need to be "released" and an updated version added to the WP plugins directory every time a new experiment is added. This is still somewhat manual process and needs a maintainer to do.

I'm a little hesitant to add this to the plugin repo for a couple reasons: 

1. None of the experiments should be shippable code — some hacky CSS is 100% fine, I think even saying "this will be part of a plugin release" makes it seem too "official."
2. Having it in the plugin repository might also legitimize it a little too much — my vision for this is more of a messy, 

> Would there be a way to retire experiments?

Yeah — for now, I figured this could be as simple as: 

1. Open an issue here to say it doesn't work. 
2. A plugin maintainer verifies and removes it. 

> Should it be possible to test more than one experiment at the same time? (I'm thinking "No" and if an experiment is an extension/tweak of another experiment, it should start by forking the "parent" CSS file. This may be a bit... too much in cases where only a few minor changes are needed, but would keep things simpler for testers imho).

I was thinking no here too — experiments may break each other, which wouldn't be great. So one at a time makes the most sense. Since these are all CSS-based, it's relatively easy to `@include` other stylesheets if you want to build on an existing experiment.

**Comment by azaozz** [comment]
> I think in general, the target audience here is people who want to build (add) experiments.

Sounds good. If the plugin is not in the WP repo, we don't need to worry about overwriting "work in progress". Then, as you say, best is to just use git or the GH app to update it, or just re-download new zip.
